###
GET http://localhost:5000/users

###
POST http://localhost:5000/user
content-Type: application/json


{
  "name": "Emon3", 
  "email": "emon3@gmail.com"
}

###
PATCH  http://localhost:5000/user/632c85ad41ce7409e0b15aa2
content-Type: application/json


{
  "name": "EmonUpdate", 
  "email": "emonU@gmail.com"
}

###
GET http://localhost:5000/user/EmonUpdate
###

DELETE http://localhost:5000/user/632c74548d5b3be82da59598 
